### ISSUE TITLE
Unable to open /usr/local/assets/defaultConf

### ISSUE THREAD

**Issue by fulleron** [nhmood/watson-ruby#97]
After installation get this:

Unable to open /usr/local/assets/defaultConf
Cannot create default, exiting...

**Comment by groovyghoul** [comment]
The exact same thing happens in Windows:

Unable to open c:/ruby200/assets/defaultConf
Cannot create default, exiting...

**Comment by nhmood** [comment]
I think this has to do with how (or which) path is being added to the load path.
assets/defaultConf should be in the same directory as the the gem itself. 
line 11 of bin/watson is SUPPOSED to add the gems executing directory to the load path but maybe that isn't working on Windows? If you uncomment line 12 `(#p($:))` it will print the load path and we can see if it is adding the right path or not

**Comment by take** [comment]
getting this in mac :O

**Comment by groovyghoul** [comment]
I uncommented the line to show the searched paths and and manually created a `c:/ruby200/assents/defaultConf` file.

Then I run the following:
C:\Ruby200\bin> `watson`

I receive the following:

```
["C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/.", "C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/assets", "C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/lib", "C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/assets", "C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/bin", "C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/lib", "C:/Ruby200/lib/ruby/site_ruby/2.0.0", "C:/Ruby200/lib/ruby/site_ruby/2.0.0/i386-msvcrt", "C:/Ruby200/lib/ruby/site_ruby", "C:/Ruby200/lib/ruby/vendor_ruby/2.0.0", "C:/Ruby200/lib/ruby/vendor_ruby/2.0.0/i386-msvcrt", "C:/Ruby200/lib/ruby/vendor_ruby", "C:/Ruby200/lib/ruby/2.0.0", "C:/Ruby200/lib/ruby/2.0.0/i386-mingw32"]

The system cannot find the path specified.

C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/lib/watson/printer.rb:153:in `cprint': undefined method `write' for nil:NilClass (NoMethodError)
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/lib/watson/printer.rb:171:in `print_header'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/lib/watson/printer.rb:122:in `run'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/lib/watson/command.rb:152:in `execute'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/bin/watson:18:in `<top (required)>'
        from C:/Ruby200/bin/watson:23:in `load'
        from C:/Ruby200/bin/watson:23:in `<main>'
```

Thanks for any more suggestions. This project looks like something I've been missing from my stack.

**Comment by alpaca-tc** [comment]
You need to fix in `lib/watson/config.rb:L180` or create .watosonrc.

This wrong regexp is a bug.
`_full_path = __dir__.gsub(/\/lib(.?)+/, '') + "/" + "assets/defaultConf"`

**Comment by nhmood** [comment]
Should be fixed with 31e573e, @take @groovyghoul @fulleron : could you guys check and make sure this is working before I close the issue?

**Comment by groovyghoul** [comment]
That commit has fixed the original problem. The `.watsonrc` file is being created properly, but when I run `watson` in Windows, I am still receiving:

```
The system cannot find the path specified.
C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/lib/watson/printer.rb:153:in `cprint': undefined method `write' for nil:NilClass (NoMethodError)
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/lib/watson/printer.rb:171:in `print_header'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/lib/watson/printer.rb:122:in `run'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/lib/watson/command.rb:152:in `execute'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.2/bin/watson:18:in `<top (required)>'
        from C:/Ruby200/bin/watson:23:in `load'
        from C:/Ruby200/bin/watson:23:in `<main>'
```

Should I report this as a different issue?

**Comment by dinapetrovic** [comment]
Getting the same error as @groovyghoul on windows. Additionally, all tests fail when running rake (both on master and [31e573e](https://github.com/nhmood/watson-ruby/commit/31e573e)).

**Comment by nhmood** [comment]
I'll grab a copy of Ruby on Windows and test this out later today so figuring out this problem will be a little easier.

In the meantime, you could edit lib/watson.rb @ line32 to `GLOBAL_DEBUG_ON = true` (or the `DEBUG` in the individual .rb file if you can identify which .rb the error is originating from)
This will force all the methods to print debug info and that might give us a better idea of where exactly it is failing

**Comment by dinapetrovic** [comment]
Running watson with `GLOBAL_DEBUG_ON = true` prints out this: https://gist.github.com/shadeless/aa2997d56943ecb5859d

Thanks for looking into it, this will most likely become one of the tools I use every day.

**Comment by groovyghoul** [comment]
Running watson with `GLOBAL_DEBUG_ON = true` prints out this:
https://gist.github.com/groovyghoul/7609361

Looks pretty similar to what @shadeless gist looks like. Thanks for taking the time for us.

**Comment by alpaca-tc** [comment]
This error is ocurred when set '@config.use_less' to false.

You should close this issue and create new one because It is unrelated bug.

**Comment by nhmood** [comment]
Yeah, from what I can see so far STDOUT returns nil on Windows, whereas on Linux it is a valid pipe (? not sure if that is the right term)

I'm looking into what the proper output on Windows is as well as how to select between the two (Windows version and Unix STDOUT) based on the OS

**Comment by nhmood** [comment]
Should be fixed with 133ccbced884149dd0d122b62e76958c9bd2a676
@groovyghoul @shadeless can you confirm this commit fixes the issue so I can close this issue?

**Comment by fulleron** [comment]
(EDIT: I guess a problem with my files, not sure if the error should be displayed this way)
After upgrading to 1.0.3 gem it shows:

```
/usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:237:in `match': invalid byte sequence in UTF-8 (ArgumentError)
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:237:in `match'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:237:in `block in parse_file'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:232:in `each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:232:in `each_with_index'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:232:in `parse_file'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:126:in `block in parse_dir'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:96:in `each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:96:in `parse_dir'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:148:in `block in parse_dir'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:135:in `each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:135:in `parse_dir'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:148:in `block in parse_dir'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:135:in `each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:135:in `parse_dir'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:148:in `block in parse_dir'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:135:in `each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:135:in `parse_dir'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:50:in `block in run'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:49:in `each'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/parser.rb:49:in `run'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/lib/watson/command.rb:151:in `execute'
    from /usr/local/lib/ruby/gems/2.0.0/gems/watson-ruby-1.0.3/bin/watson:18:in `<top (required)>'
    from /usr/local/bin/watson:23:in `load'
    from /usr/local/bin/watson:23:in `<main>'
```

**Comment by nhmood** [comment]
@fulleron the error you are seeing has to do with watson trying to parse a binary (or non UTF8) file. 
I will release 1.0.4 when I pull in the changes from @hunterboerner to fix the nonUTF8 problem so that both the Windows cprint error as well as the nonUTF8 are fixed

**Comment by fulleron** [comment]
@nhmood thank you so much :) looking forward to using your tool

**Comment by dinapetrovic** [comment]
Watson now works, but gives weird output. Running [133ccbc](https://github.com/nhmood/watson-ruby/commit/133ccbced884149dd0d122b62e76958c9bd2a676) in watson directory with cygwin and zsh: [watson-test](http://i.imgur.com/PD5ebvk.png)

**Comment by nhmood** [comment]
@shadeless this should be fixed with https://github.com/nhmood/watson-ruby/pull/111, I am just testing to make sure it doesn't break anything in Unix before merging

**Comment by nhmood** [comment]
@shadeless Fixed with 1e6bf78242269a7bbc42dfb633f45fc5eb470c52, RubyGem updated to 1.0.5 https://rubygems.org/gems/watson-ruby
